### ISSUE TITLE
Installation fails (path '/Users/julianporter/git/FLPFiles/src/parse_flp' cannot be absolute)

### ISSUE THREAD

**Issue by ghost** [jdstmporter/FLPFiles#2]
`pip install flpfile` throws
```
Collecting flpfile
  Downloading FLPFile-0.2.0.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Packages is "['FLP', 'FLP.chunks', 'FLP.messagetypes', 'FLP.messagetypes.text']"
      running egg_info
      writing src\FLPFile.egg-info\PKG-INFO
      writing dependency_links to src\FLPFile.egg-info\dependency_links.txt
      writing top-level names to src\FLPFile.egg-info\top_level.txt
      reading manifest file 'src\FLPFile.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\qjnri\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\qjnri\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\qjnri\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 317, in run
          self.find_sources()
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 325, in find_sources
          mm.run()
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 573, in run
          self.add_defaults()
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 618, in add_defaults
          self.read_manifest()
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\command\sdist.py", line 209, in read_manifest
          self.filelist.append(line)
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 510, in append
          path = convert_path(item)
        File "C:\Users\qjnri\AppData\Local\Temp\pip-build-env-fy37osup\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/julianporter/git/FLPFiles/src/parse_flp' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

(Running this on Windows 10)

Looks like you have left an absolute path from your own system in the build script by accident (`ValueError: path `**`'/Users/julianporter/git/FLPFiles/src/parse_flp'`**` cannot be absolute`.

**Comment by ghost** [comment]
On Linux (Ubuntu WSL2) it also fails with the following error:
```
Collecting flpfile
  Downloading FLPFile-0.2.0.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: flpfile
  Building wheel for flpfile (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpzhtonene build_wheel /tmp/tmpjzyl89je
       cwd: /tmp/pip-install-jc9g0h7n/flpfile
  Complete output (64 lines):
  Packages is "['FLP', 'FLP.messagetypes', 'FLP.chunks', 'FLP.messagetypes.text']"
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/FLP
  copying src/FLP/partitioner.py -> build/lib/FLP
  copying src/FLP/base.py -> build/lib/FLP
  copying src/FLP/__init__.py -> build/lib/FLP
  creating build/lib/FLP/messagetypes
  copying src/FLP/messagetypes/int8messages.py -> build/lib/FLP/messagetypes
  copying src/FLP/messagetypes/core.py -> build/lib/FLP/messagetypes
  copying src/FLP/messagetypes/textmessages.py -> build/lib/FLP/messagetypes
  copying src/FLP/messagetypes/int32messages.py -> build/lib/FLP/messagetypes
  copying src/FLP/messagetypes/int16messages.py -> build/lib/FLP/messagetypes
  copying src/FLP/messagetypes/__init__.py -> build/lib/FLP/messagetypes
  creating build/lib/FLP/chunks
  copying src/FLP/chunks/track.py -> build/lib/FLP/chunks
  copying src/FLP/chunks/chunk.py -> build/lib/FLP/chunks
  copying src/FLP/chunks/header.py -> build/lib/FLP/chunks
  copying src/FLP/chunks/__init__.py -> build/lib/FLP/chunks
  copying src/FLP/chunks/event.py -> build/lib/FLP/chunks
  creating build/lib/FLP/messagetypes/text
  copying src/FLP/messagetypes/text/text.py -> build/lib/FLP/messagetypes/text
  copying src/FLP/messagetypes/text/numeric.py -> build/lib/FLP/messagetypes/text
  copying src/FLP/messagetypes/text/base.py -> build/lib/FLP/messagetypes/text
  copying src/FLP/messagetypes/text/defs.py -> build/lib/FLP/messagetypes/text
  copying src/FLP/messagetypes/text/__init__.py -> build/lib/FLP/messagetypes/text
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/FLP
  creating build/bdist.linux-x86_64/wheel/FLP/messagetypes
  copying build/lib/FLP/messagetypes/int8messages.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes
  creating build/bdist.linux-x86_64/wheel/FLP/messagetypes/text
  copying build/lib/FLP/messagetypes/text/text.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes/text
  copying build/lib/FLP/messagetypes/text/numeric.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes/text
  copying build/lib/FLP/messagetypes/text/base.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes/text
  copying build/lib/FLP/messagetypes/text/defs.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes/text
  copying build/lib/FLP/messagetypes/text/__init__.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes/text
  copying build/lib/FLP/messagetypes/core.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes
  copying build/lib/FLP/messagetypes/textmessages.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes
  copying build/lib/FLP/messagetypes/int32messages.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes
  copying build/lib/FLP/messagetypes/int16messages.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes
  copying build/lib/FLP/messagetypes/__init__.py -> build/bdist.linux-x86_64/wheel/FLP/messagetypes
  creating build/bdist.linux-x86_64/wheel/FLP/chunks
  copying build/lib/FLP/chunks/track.py -> build/bdist.linux-x86_64/wheel/FLP/chunks
  copying build/lib/FLP/chunks/chunk.py -> build/bdist.linux-x86_64/wheel/FLP/chunks
  copying build/lib/FLP/chunks/header.py -> build/bdist.linux-x86_64/wheel/FLP/chunks
  copying build/lib/FLP/chunks/__init__.py -> build/bdist.linux-x86_64/wheel/FLP/chunks
  copying build/lib/FLP/chunks/event.py -> build/bdist.linux-x86_64/wheel/FLP/chunks
  copying build/lib/FLP/partitioner.py -> build/bdist.linux-x86_64/wheel/FLP
  copying build/lib/FLP/base.py -> build/bdist.linux-x86_64/wheel/FLP
  copying build/lib/FLP/__init__.py -> build/bdist.linux-x86_64/wheel/FLP
  running install_data
  creating build/bdist.linux-x86_64/wheel/FLPFile-0.2.0.data
  creating build/bdist.linux-x86_64/wheel/FLPFile-0.2.0.data/data
  creating build/bdist.linux-x86_64/wheel/usr
  creating build/bdist.linux-x86_64/wheel/usr/local
  creating build/bdist.linux-x86_64/wheel/usr/local/bin
  error: can't copy '/tmp/pip-install-jc9g0h7n/flpfile/src/parse_flp': doesn't exist or not a regular file
  ----------------------------------------
  ERROR: Failed building wheel for flpfile
Failed to build flpfile
ERROR: Could not build wheels for flpfile which use PEP 517 and cannot be installed directly
```
Seems to be slightly different but related to the same `src/parse_flp` file.
